# fly.toml app configuration file generated for go-crud-api on 2023-08-16T13:33:33-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "go-crud-api"
primary_region = "gru"

[build]
builder = "paketobuildpacks/builder:base"
buildpacks = ["gcr.io/paketo-buildpacks/go"]

[build.args]
BP_GO_TARGETS = "./cmd/server/"

[env]
DB_HOST = "0.0.0.0"
DB_PORT = "5432"
DB_USER = "admin"
DB_PASS = "admin"
DB_NAME = "geral"
JWT_SECRET = "secret"
JWT_ALG = "HS256"
JWT_EXP = "43200"
SERVER_HOST = "0.0.0.0"
SERVER_PORT = "8001"
DEBUG = "true"
PRODUCTION = "true"

[mounts]
source = "godata"
destination = "/data"
size = "0.3"


[http_service]
internal_port = 8001
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
